
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
    - name: 1st
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
    - name: 2nd
      image: debian
      command: ["sh", "-c", "while true; do date >> /html/index.html; sleep 1; done"]
      volumeMounts:
        - mountPath: /html
          name: html
  volumes:
    - name: html
      emptyDir: {}