
apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8000
          name: http
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3